apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: rarnaud-python-0
  janus-idp.io/tekton: rarnaud-python-0
  backstage.io/kubernetes-id: rarnaud-python-0
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: rarnaud-python-0
resources:
- deployment.yaml
- route.yaml
- service.yaml
