apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: rarnaud-python-0
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: rarnaud-python-0 
  name: rarnaud-python-0
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: rarnaud-python-0 
